/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JRadioButton;

/**
 *
 * @author LUISS
 */
public class MainForm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        ComboBoxFuentes.addActionListener(this);
        CheckBoxCursivas.addActionListener(this);
        checkboxNegritas.addActionListener(this);
        RadioButtonGrande.addActionListener(this);
        RadioButtonMediano.addActionListener(this);
        RadioButtonPequeno.addActionListener(this);
        ComboBoxFuentes.setSelectedIndex(0);  
        CheckBoxCursivas.setSelected(false);
        checkboxNegritas.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTamano = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiquetaTexto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        checkboxNegritas = new javax.swing.JCheckBox();
        CheckBoxCursivas = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        RadioButtonPequeno = new javax.swing.JRadioButton();
        RadioButtonMediano = new javax.swing.JRadioButton();
        RadioButtonGrande = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        ComboBoxFuentes = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemCerrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCopiar = new javax.swing.JMenuItem();
        jMenuItemCortar = new javax.swing.JMenuItem();
        jMenuItemPegar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItemBecado = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemMonologado = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuSexo = new javax.swing.JMenu();
        jRadioButtonMenuItemMasculino = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemFemenino = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCambioayuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTexto.setText("Instituto Tecnologico de Campeche");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(etiquetaTexto)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estilo"));

        checkboxNegritas.setSelected(true);
        checkboxNegritas.setText("Negritas");

        CheckBoxCursivas.setText("Cursivas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxNegritas)
                    .addComponent(CheckBoxCursivas))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkboxNegritas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxCursivas)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tamaño"));

        buttonGroupTamano.add(RadioButtonPequeno);
        RadioButtonPequeno.setSelected(true);
        RadioButtonPequeno.setText("Pequeño");

        buttonGroupTamano.add(RadioButtonMediano);
        RadioButtonMediano.setText("Mediano");

        buttonGroupTamano.add(RadioButtonGrande);
        RadioButtonGrande.setText("Grande");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonPequeno)
                    .addComponent(RadioButtonMediano)
                    .addComponent(RadioButtonGrande))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioButtonPequeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonMediano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonGrande)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fuente"));

        ComboBoxFuentes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Times New Roman", "Calibri", "Tahoma", "Consolas", "Verdana" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ComboBoxFuentes, 0, 126, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ComboBoxFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuevo.png"))); // NOI18N
        jMenuItemNuevo.setText("Nuevo...");
        jMenu1.add(jMenuItemNuevo);

        jMenuItemAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Abrir.png"))); // NOI18N
        jMenuItemAbrir.setText("Abrir...");
        jMenu1.add(jMenuItemAbrir);

        jMenuItemCerrar.setText("Cerrar");
        jMenu1.add(jMenuItemCerrar);
        jMenu1.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        jMenuItemSalir.setText("Salir");
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItemCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Copiar.png"))); // NOI18N
        jMenuItemCopiar.setText("Copiar");
        jMenu2.add(jMenuItemCopiar);

        jMenuItemCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cortar.png"))); // NOI18N
        jMenuItemCortar.setText("Cortar");
        jMenu2.add(jMenuItemCortar);

        jMenuItemPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pegar.png"))); // NOI18N
        jMenuItemPegar.setText("Pegar");
        jMenu2.add(jMenuItemPegar);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Demo");

        jCheckBoxMenuItemBecado.setText("Becado");
        jMenu4.add(jCheckBoxMenuItemBecado);

        jCheckBoxMenuItemMonologado.setText("Monologado");
        jMenu4.add(jCheckBoxMenuItemMonologado);
        jMenu4.add(jSeparator3);

        jMenuSexo.setText("Sexo");

        jRadioButtonMenuItemMasculino.setSelected(true);
        jRadioButtonMenuItemMasculino.setText("Masculino");
        jMenuSexo.add(jRadioButtonMenuItemMasculino);

        jRadioButtonMenuItemFemenino.setText("Femenino");
        jMenuSexo.add(jRadioButtonMenuItemFemenino);

        jMenu4.add(jMenuSexo);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Ayuda");

        jMenuItemCambioayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario.png"))); // NOI18N
        jMenuItemCambioayuda.setText("Cambio de ayuda...");
        jMenu3.add(jMenuItemCambioayuda);
        jMenu3.add(jSeparator2);

        jMenuItemAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Acerca de.png"))); // NOI18N
        jMenuItemAcerca.setText("Acerca de...");
        jMenu3.add(jMenuItemAcerca);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel2, jPanel3, jPanel4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxCursivas;
    private javax.swing.JComboBox ComboBoxFuentes;
    private javax.swing.JRadioButton RadioButtonGrande;
    private javax.swing.JRadioButton RadioButtonMediano;
    private javax.swing.JRadioButton RadioButtonPequeno;
    private javax.swing.ButtonGroup buttonGroupTamano;
    private javax.swing.JCheckBox checkboxNegritas;
    private javax.swing.JLabel etiquetaTexto;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemBecado;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemMonologado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemAcerca;
    private javax.swing.JMenuItem jMenuItemCambioayuda;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemCopiar;
    private javax.swing.JMenuItem jMenuItemCortar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemPegar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuSexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemFemenino;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemMasculino;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
    Object sr = e.getSource();
//    String letra = "" ;
            
    if(sr == ComboBoxFuentes){
//        int LetrasFuentes = ComboBoxFuentes.getSelectedIndex(); 0 hasta las que tenga
        String LetrasFuentes = ""+ComboBoxFuentes.getSelectedItem();
        System.out.println(LetrasFuentes);
    }else if(sr == CheckBoxCursivas){
       
    }else if(sr == checkboxNegritas){
        
    }else if(sr == RadioButtonGrande){
        this.verificarTamano(RadioButtonGrande);
    }else if(sr == RadioButtonMediano){
        this.verificarTamano(RadioButtonMediano);
    }else if(sr == RadioButtonPequeno){
        this.verificarTamano(RadioButtonPequeno);
    }
    ///////
//    if(CheckBoxCursivas.isSelected() == true){
//        System.out.println("Cursivas ");
//    }else if(checkboxNegritas.isSelected() == true){
//        System.out.println("Negritas ");
//    }
//    if(CheckBoxCursivas.isSelected()){
//        letra = "cursivas";
//        System.out.println(letra);
//    }else{
//        
//    }
//    
//    if(checkboxNegritas.isSelected()){
//        letra = "negritas";
//        System.out.println(letra);
//    }else{
//        
//    }
        
    }
    
    private void verificarTamano(JRadioButton boton){
        if(boton.isSelected() == true){
            System.out.println("Tamaño letra "+boton.getText());
        }
    }
}
